alpha_out: 1.0
beta_cons: 10.0
gamma_adv: 1.0
rep_dim: 64
phi_layers: [128]
head_layers: [64]
disc_layers: [64]
activation: relu
lr_g: 0.001
lr_d: 0.001
optimizer: adam
opt_g_kwargs: {}
opt_d_kwargs: {}
epochs: 30
grad_clip: 2.0
warm_start: 0
use_wgan_gp: false
spectral_norm: false
feature_matching: false
label_smoothing: false
instance_noise: false
gradient_reversal: false
ttur: false
lambda_gp: 10.0
eta_fm: 5.0
grl_weight: 1.0
tensorboard_logdir: null
weight_clip: null
patience: 0
