alpha_out: 1.0
beta_cons: 10.0
gamma_adv: 1.0
rep_dim: 64
phi_layers: [128]
head_layers: [64]
disc_layers: [64]
disc_pack: 1
activation: relu
phi_dropout: 0.0
head_dropout: 0.0
disc_dropout: 0.0
lr_g: 0.001
lr_d: 0.001
optimizer: adam
opt_g_kwargs: {}
opt_d_kwargs: {}
epochs: 30
grad_clip: 2.0
warm_start: 0
use_wgan_gp: false
adv_loss: bce
ema_decay: null
spectral_norm: false
feature_matching: false
label_smoothing: false
instance_noise: false
gradient_reversal: false
ttur: false
lambda_gp: 10.0
r1_gamma: 0.0
r2_gamma: 0.0
adaptive_reg: false
d_reg_lower: 0.3
d_reg_upper: 0.7
reg_factor: 1.1
lambda_gp_min: 0.001
lambda_gp_max: 100.0
unrolled_steps: 0
eta_fm: 5.0
grl_weight: 1.0
contrastive_weight: 0.0
contrastive_margin: 1.0
contrastive_noise: 0.0
tensorboard_logdir: null
weight_clip: null
patience: 0
